# Generated by Django 2.0 on 2017-12-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('screen', models.CharField(max_length=2048)),
                ('created_at', models.IntegerField()),
            ],
        ),
    ]
