# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeuxvideo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeux',
            old_name='created_at',
            new_name='first_release_date',
        ),
        migrations.RemoveField(
            model_name='jeux',
            name='screen',
        ),
        migrations.AddField(
            model_name='jeux',
            name='cover',
            field=models.CharField(default='Image non trouvée', max_length=64),
            preserve_default=False,
        ),
    ]
