# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='date_sortie',
            field=models.DateField(null=True),
        ),
    ]
