# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:20
from __future__ import unicode_literals

from django.db import migrations


def migrer_artiste(apps, schema):
    Morceau = apps.get_model('musiques.Morceau')
    Artiste = apps.get_model('musiques.Artiste')
    artistes = {m.artiste for m in Morceau.objects.all()}
    for nom in artistes:
        Artiste.objects.create(nom=nom)


def annuler_migrer_artiste(apps, schema):
    Artiste = apps.get_model('musiques.Artiste')
    for a in Artiste.objects.all():
        a.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0003_auto_20171005_0919'),
    ]

    operations = [
        migrations.RunPython(
            migrer_artiste, reverse_code=annuler_migrer_artiste)
    ]
