# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 06:44
from __future__ import unicode_literals

from django.db import migrations


def ajouter_fk_artiste(apps, schema):
    Morceau = apps.get_model('musiques', 'Morceau')
    Artiste = apps.get_model('musiques', 'Artiste')
    for m in Morceau.objects.all():
        a = Artiste.objects.get(nom=m.artiste)
        m.artiste_fk = a
        m.save()


def delete_fk_artiste(apps, schema):
    Morceau = apps.get_model('musiques', 'Morceau')
    Morceau.objects.all().update(artiste_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0004_auto_20171005_0920'),
    ]

    operations = [
        migrations.RunPython(ajouter_fk_artiste,
                             reverse_code=delete_fk_artiste)
    ]
