# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0005_auto_20171006_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='artiste',
        ),

    ]
