# Generated by Django 2.0 on 2017-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='sortie',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=230),
        ),
    ]
